spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow
    username: flow
    password: flow_pwd
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

base:
  folder:
    path: /tmp/flow/